name: venue
description: Create a new Flutter project.
dependencies:
  flutter:
    path: /home/seve/lib/flutter/packages/flutter
  venue_api_dart:
    git:
      url: git@github.com:rcos/venue-api-dart.git
      branch: flutter
