name: venue
description: Create a new Flutter project.
dependencies:
  flutter:
    path: /home/seve/lib/flutter/packages/flutter
  venue_api_dart:
    path: "/home/seve/workspace/venue-api-dart"
    # git:
    #   url: git@github.com:rcos/venue-api-dart.git
    #   branch: flutter
